version: '2'
services:
  odoo_web:
    image: odoo:latest
    container_name: odoo_web
    depends_on:
      - odoo_db
    environment:
      - PGPORT=5433
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/odoo_data:/home/odoo
      - ../:/opt/odoo
  odoo_db:
    image: postgres:latest
    container_name: odoo_db
    environment:
      - PGPORT=5433
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5433"
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
